# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/companies.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Companies(object):
    def setupUi(self, Companies):
        Companies.setObjectName("Companies")
        Companies.resize(800, 627)
        self.centralwidget = QtWidgets.QWidget(Companies)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(60, 80, 681, 451))
        self.stackedWidget.setObjectName("stackedWidget")
        self.pg_info = QtWidgets.QWidget()
        self.pg_info.setObjectName("pg_info")
        self.layoutWidget = QtWidgets.QWidget(self.pg_info)
        self.layoutWidget.setGeometry(QtCore.QRect(170, 20, 331, 163))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(40)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.lb_date = QtWidgets.QLabel(self.layoutWidget)
        self.lb_date.setObjectName("lb_date")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lb_date)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.dateTimeEdit.setReadOnly(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateTimeEdit)
        self.lb_balance = QtWidgets.QLabel(self.layoutWidget)
        self.lb_balance.setObjectName("lb_balance")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lb_balance)
        self.line_basic_bal = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_basic_bal.setReadOnly(True)
        self.line_basic_bal.setObjectName("line_basic_bal")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_basic_bal)
        self.lb_total_b = QtWidgets.QLabel(self.layoutWidget)
        self.lb_total_b.setObjectName("lb_total_b")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lb_total_b)
        self.line_basic_borr = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_basic_borr.setReadOnly(True)
        self.line_basic_borr.setObjectName("line_basic_borr")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.line_basic_borr)
        self.lb_total_l = QtWidgets.QLabel(self.layoutWidget)
        self.lb_total_l.setObjectName("lb_total_l")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lb_total_l)
        self.line_basic_lent = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_basic_lent.setReadOnly(True)
        self.line_basic_lent.setObjectName("line_basic_lent")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.line_basic_lent)
        self.table_info_bor = QtWidgets.QTableWidget(self.pg_info)
        self.table_info_bor.setGeometry(QtCore.QRect(60, 220, 561, 91))
        self.table_info_bor.setObjectName("table_info_bor")
        self.table_info_bor.setColumnCount(0)
        self.table_info_bor.setRowCount(0)
        self.table_info_lent = QtWidgets.QTableWidget(self.pg_info)
        self.table_info_lent.setGeometry(QtCore.QRect(60, 340, 561, 91))
        self.table_info_lent.setObjectName("table_info_lent")
        self.table_info_lent.setColumnCount(0)
        self.table_info_lent.setRowCount(0)
        self.lb_borrowed = QtWidgets.QLabel(self.pg_info)
        self.lb_borrowed.setGeometry(QtCore.QRect(290, 200, 67, 17))
        self.lb_borrowed.setObjectName("lb_borrowed")
        self.lb_lent = QtWidgets.QLabel(self.pg_info)
        self.lb_lent.setGeometry(QtCore.QRect(310, 320, 28, 17))
        self.lb_lent.setObjectName("lb_lent")
        self.stackedWidget.addWidget(self.pg_info)
        self.pg_trans = QtWidgets.QWidget()
        self.pg_trans.setObjectName("pg_trans")
        self.lb_borrowed_trans = QtWidgets.QLabel(self.pg_trans)
        self.lb_borrowed_trans.setGeometry(QtCore.QRect(300, 30, 201, 31))
        self.lb_borrowed_trans.setObjectName("lb_borrowed_trans")
        self.btn_submit_trans = QtWidgets.QPushButton(self.pg_trans)
        self.btn_submit_trans.setGeometry(QtCore.QRect(210, 340, 93, 28))
        self.btn_submit_trans.setObjectName("btn_submit_trans")
        self.btn_reset_trans = QtWidgets.QPushButton(self.pg_trans)
        self.btn_reset_trans.setGeometry(QtCore.QRect(360, 340, 93, 28))
        self.btn_reset_trans.setObjectName("btn_reset_trans")
        self.layoutWidget1 = QtWidgets.QWidget(self.pg_trans)
        self.layoutWidget1.setGeometry(QtCore.QRect(150, 180, 371, 121))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget1)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lb_from_trans = QtWidgets.QLabel(self.layoutWidget1)
        self.lb_from_trans.setObjectName("lb_from_trans")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lb_from_trans)
        self.line_trans_from = QtWidgets.QLineEdit(self.layoutWidget1)
        self.line_trans_from.setObjectName("line_trans_from")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_trans_from)
        self.lb_to_trans = QtWidgets.QLabel(self.layoutWidget1)
        self.lb_to_trans.setObjectName("lb_to_trans")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lb_to_trans)
        self.line_trans_to = QtWidgets.QLineEdit(self.layoutWidget1)
        self.line_trans_to.setObjectName("line_trans_to")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_trans_to)
        self.lb_amount_trans = QtWidgets.QLabel(self.layoutWidget1)
        self.lb_amount_trans.setObjectName("lb_amount_trans")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lb_amount_trans)
        self.line_trans_amt = QtWidgets.QLineEdit(self.layoutWidget1)
        self.line_trans_amt.setObjectName("line_trans_amt")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.line_trans_amt)
        self.lb_date_trans = QtWidgets.QLabel(self.layoutWidget1)
        self.lb_date_trans.setObjectName("lb_date_trans")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lb_date_trans)
        self.line_trans_due = QtWidgets.QLineEdit(self.layoutWidget1)
        self.line_trans_due.setObjectName("line_trans_due")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.line_trans_due)
        self.table_trans_lent = QtWidgets.QTableWidget(self.pg_trans)
        self.table_trans_lent.setGeometry(QtCore.QRect(150, 60, 371, 91))
        self.table_trans_lent.setObjectName("table_trans_lent")
        self.table_trans_lent.setColumnCount(0)
        self.table_trans_lent.setRowCount(0)
        self.stackedWidget.addWidget(self.pg_trans)
        self.pg_pur = QtWidgets.QWidget()
        self.pg_pur.setObjectName("pg_pur")
        self.label_2 = QtWidgets.QLabel(self.pg_pur)
        self.label_2.setGeometry(QtCore.QRect(270, 30, 121, 21))
        self.label_2.setObjectName("label_2")
        self.layoutWidget2 = QtWidgets.QWidget(self.pg_pur)
        self.layoutWidget2.setGeometry(QtCore.QRect(160, 80, 361, 117))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.layoutWidget2)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setHorizontalSpacing(30)
        self.formLayout_3.setVerticalSpacing(20)
        self.formLayout_3.setObjectName("formLayout_3")
        self.lb_to_pur = QtWidgets.QLabel(self.layoutWidget2)
        self.lb_to_pur.setObjectName("lb_to_pur")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lb_to_pur)
        self.line_pur_to = QtWidgets.QLineEdit(self.layoutWidget2)
        self.line_pur_to.setObjectName("line_pur_to")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_pur_to)
        self.lb_amount_pur = QtWidgets.QLabel(self.layoutWidget2)
        self.lb_amount_pur.setObjectName("lb_amount_pur")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lb_amount_pur)
        self.line_pur_amt = QtWidgets.QLineEdit(self.layoutWidget2)
        self.line_pur_amt.setObjectName("line_pur_amt")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_pur_amt)
        self.lb_date_pur = QtWidgets.QLabel(self.layoutWidget2)
        self.lb_date_pur.setObjectName("lb_date_pur")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lb_date_pur)
        self.line_pur_due = QtWidgets.QLineEdit(self.layoutWidget2)
        self.line_pur_due.setObjectName("line_pur_due")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.line_pur_due)
        self.layoutWidget3 = QtWidgets.QWidget(self.pg_pur)
        self.layoutWidget3.setGeometry(QtCore.QRect(200, 240, 252, 27))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(90)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_submit_pur = QtWidgets.QPushButton(self.layoutWidget3)
        self.btn_submit_pur.setObjectName("btn_submit_pur")
        self.horizontalLayout_4.addWidget(self.btn_submit_pur)
        self.btn_reset_pur = QtWidgets.QPushButton(self.layoutWidget3)
        self.btn_reset_pur.setObjectName("btn_reset_pur")
        self.horizontalLayout_4.addWidget(self.btn_reset_pur)
        self.stackedWidget.addWidget(self.pg_pur)
        self.pg_borrow = QtWidgets.QWidget()
        self.pg_borrow.setObjectName("pg_borrow")
        self.label = QtWidgets.QLabel(self.pg_borrow)
        self.label.setGeometry(QtCore.QRect(210, 50, 381, 41))
        self.label.setObjectName("label")
        self.layoutWidget4 = QtWidgets.QWidget(self.pg_borrow)
        self.layoutWidget4.setGeometry(QtCore.QRect(140, 110, 381, 101))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.layoutWidget4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setHorizontalSpacing(40)
        self.formLayout_4.setVerticalSpacing(30)
        self.formLayout_4.setObjectName("formLayout_4")
        self.lb_amount_borrow = QtWidgets.QLabel(self.layoutWidget4)
        self.lb_amount_borrow.setObjectName("lb_amount_borrow")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lb_amount_borrow)
        self.line_borr_amt = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_borr_amt.setObjectName("line_borr_amt")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_borr_amt)
        self.lb_date_borrow = QtWidgets.QLabel(self.layoutWidget4)
        self.lb_date_borrow.setObjectName("lb_date_borrow")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lb_date_borrow)
        self.line_borr_due = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_borr_due.setObjectName("line_borr_due")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_borr_due)
        self.layoutWidget5 = QtWidgets.QWidget(self.pg_borrow)
        self.layoutWidget5.setGeometry(QtCore.QRect(200, 250, 242, 27))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(80)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_submit_bor = QtWidgets.QPushButton(self.layoutWidget5)
        self.btn_submit_bor.setObjectName("btn_submit_bor")
        self.horizontalLayout_5.addWidget(self.btn_submit_bor)
        self.btn_reset_bor = QtWidgets.QPushButton(self.layoutWidget5)
        self.btn_reset_bor.setObjectName("btn_reset_bor")
        self.horizontalLayout_5.addWidget(self.btn_reset_bor)
        self.stackedWidget.addWidget(self.pg_borrow)
        self.layoutWidget6 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget6.setGeometry(QtCore.QRect(150, 40, 514, 30))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(25)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_info = QtWidgets.QPushButton(self.layoutWidget6)
        self.btn_info.setObjectName("btn_info")
        self.horizontalLayout.addWidget(self.btn_info)
        self.btn_transfer = QtWidgets.QPushButton(self.layoutWidget6)
        self.btn_transfer.setObjectName("btn_transfer")
        self.horizontalLayout.addWidget(self.btn_transfer)
        self.btn_purchasing = QtWidgets.QPushButton(self.layoutWidget6)
        self.btn_purchasing.setObjectName("btn_purchasing")
        self.horizontalLayout.addWidget(self.btn_purchasing)
        self.btn_borrowing = QtWidgets.QPushButton(self.layoutWidget6)
        self.btn_borrowing.setObjectName("btn_borrowing")
        self.horizontalLayout.addWidget(self.btn_borrowing)
        self.btn_quit = QtWidgets.QPushButton(self.layoutWidget6)
        self.btn_quit.setObjectName("btn_quit")
        self.horizontalLayout.addWidget(self.btn_quit)
        Companies.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Companies)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        Companies.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Companies)
        self.statusbar.setObjectName("statusbar")
        Companies.setStatusBar(self.statusbar)

        self.retranslateUi(Companies)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Companies)

    def retranslateUi(self, Companies):
        _translate = QtCore.QCoreApplication.translate
        Companies.setWindowTitle(_translate("Companies", "MainWindow"))
        self.lb_date.setText(_translate("Companies", "Date"))
        self.lb_balance.setText(_translate("Companies", "Balance"))
        self.lb_total_b.setText(_translate("Companies", "Total borrowed"))
        self.lb_total_l.setText(_translate("Companies", "Total lent"))
        self.lb_borrowed.setText(_translate("Companies", "borrowed"))
        self.lb_lent.setText(_translate("Companies", "lent"))
        self.lb_borrowed_trans.setText(_translate("Companies", "Lent List"))
        self.btn_submit_trans.setText(_translate("Companies", "Submit"))
        self.btn_reset_trans.setText(_translate("Companies", "Reset"))
        self.lb_from_trans.setText(_translate("Companies", "From"))
        self.lb_to_trans.setText(_translate("Companies", "To"))
        self.lb_amount_trans.setText(_translate("Companies", "Amount"))
        self.lb_date_trans.setText(_translate("Companies", "Due Date"))
        self.label_2.setText(_translate("Companies", "Purchasing Form"))
        self.lb_to_pur.setText(_translate("Companies", "To"))
        self.lb_amount_pur.setText(_translate("Companies", "Amount"))
        self.lb_date_pur.setText(_translate("Companies", "Due Date"))
        self.btn_submit_pur.setText(_translate("Companies", "Submit"))
        self.btn_reset_pur.setText(_translate("Companies", "Reset"))
        self.label.setText(_translate("Companies", "You are borrowing from bank..."))
        self.lb_amount_borrow.setText(_translate("Companies", "Amount"))
        self.lb_date_borrow.setText(_translate("Companies", "Due date"))
        self.btn_submit_bor.setText(_translate("Companies", "Submit"))
        self.btn_reset_bor.setText(_translate("Companies", "Reset"))
        self.btn_info.setText(_translate("Companies", "Basic Info"))
        self.btn_transfer.setText(_translate("Companies", "Transfer"))
        self.btn_purchasing.setText(_translate("Companies", "Purchasing"))
        self.btn_borrowing.setText(_translate("Companies", "Borrowing"))
        self.btn_quit.setText(_translate("Companies", "Quit"))
