# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/manager.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Manager(object):
    def setupUi(self, Manager):
        Manager.setObjectName("Manager")
        Manager.resize(457, 366)
        self.centralwidget = QtWidgets.QWidget(Manager)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(50, 80, 351, 251))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_register = QtWidgets.QWidget()
        self.page_register.setObjectName("page_register")
        self.label = QtWidgets.QLabel(self.page_register)
        self.label.setGeometry(QtCore.QRect(80, 20, 181, 31))
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.page_register)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 70, 215, 112))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setVerticalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.edit_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.edit_name.setObjectName("edit_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edit_name)
        self.label_pwd = QtWidgets.QLabel(self.layoutWidget)
        self.label_pwd.setObjectName("label_pwd")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_pwd)
        self.edit_pwd = QtWidgets.QLineEdit(self.layoutWidget)
        self.edit_pwd.setObjectName("edit_pwd")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edit_pwd)
        self.label_name = QtWidgets.QLabel(self.layoutWidget)
        self.label_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name.setObjectName("label_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_name)
        self.layoutWidget1 = QtWidgets.QWidget(self.page_register)
        self.layoutWidget1.setGeometry(QtCore.QRect(70, 210, 211, 27))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_register = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_register.setObjectName("btn_register")
        self.horizontalLayout.addWidget(self.btn_register)
        self.btn_reset = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_reset.setObjectName("btn_reset")
        self.horizontalLayout.addWidget(self.btn_reset)
        self.stackedWidget.addWidget(self.page_register)
        self.page_info = QtWidgets.QWidget()
        self.page_info.setObjectName("page_info")
        self.text_info = QtWidgets.QLabel(self.page_info)
        self.text_info.setGeometry(QtCore.QRect(60, 0, 231, 41))
        self.text_info.setObjectName("text_info")
        self.table = QtWidgets.QTableWidget(self.page_info)
        self.table.setGeometry(QtCore.QRect(20, 40, 321, 171))
        self.table.setObjectName("table")
        self.table.setColumnCount(3)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        self.stackedWidget.addWidget(self.page_info)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(60, 30, 331, 31))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(40)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_select_register = QtWidgets.QPushButton(self.layoutWidget2)
        self.btn_select_register.setObjectName("btn_select_register")
        self.horizontalLayout_2.addWidget(self.btn_select_register)
        self.btn_select_list = QtWidgets.QPushButton(self.layoutWidget2)
        self.btn_select_list.setObjectName("btn_select_list")
        self.horizontalLayout_2.addWidget(self.btn_select_list)
        self.btn_quit = QtWidgets.QPushButton(self.layoutWidget2)
        self.btn_quit.setObjectName("btn_quit")
        self.horizontalLayout_2.addWidget(self.btn_quit)
        Manager.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Manager)
        self.statusbar.setObjectName("statusbar")
        Manager.setStatusBar(self.statusbar)

        self.retranslateUi(Manager)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Manager)

    def retranslateUi(self, Manager):
        _translate = QtCore.QCoreApplication.translate
        Manager.setWindowTitle(_translate("Manager", "MainWindow"))
        self.label.setText(_translate("Manager", "Register A New Company"))
        self.label_pwd.setText(_translate("Manager", "Password"))
        self.label_name.setText(_translate("Manager", "Name"))
        self.btn_register.setText(_translate("Manager", "Register"))
        self.btn_reset.setText(_translate("Manager", "Reset"))
        self.text_info.setText(_translate("Manager", "Info of All Registered Companies"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("Manager", "Name"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("Manager", "Type"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("Manager", "Address"))
        self.btn_select_register.setText(_translate("Manager", "Register"))
        self.btn_select_list.setText(_translate("Manager", "List All"))
        self.btn_quit.setText(_translate("Manager", "Quit"))
